<?php

use App\Product;
use App\ProductImage;
use App\ProductOption;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {     
       
        $items = [
            ['ItemImage' => "products/22s.png",  'whole' => 2 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => '25M 79mm Thermal Paper roll for Cashier', 'ItemName' => 'بكر حراري 25 متر  7.9 سم لطابعات الكاشير', 'ItemImageWhole' => 'products/22.png', 'POSTP' => '561.6', 'POSPP' => '3.9', 'MinorPerMajor' => '144', 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 1],
            ['ItemImage' => "products/27s.png",  'whole' => 2 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => '55M 79mm Thermal Paper roll for Cashier', 'ItemName' => 'بكر حراري 55 متر  7.9 سم لطابعات الكاشير', 'ItemImageWhole' => 'products/27.png', 'POSTP' => '576', 'POSPP' => '9', 'MinorPerMajor' => '64', 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 1],
            ['ItemImage' => "products/28s.png",  'whole' => 2 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => '70M 79mm Thermal Paper roll for Cashier 60 roll box', 'ItemName' => 'بكر حراري 70 متر  7.9 سم لطابعات الكاشير كارتونة 60 بكرة', 'ItemImageWhole' => 'products/28.png', 'POSTP' => '660', 'POSPP' => '11', 'MinorPerMajor' => '60', 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 1],
            ['ItemImage' => "products/29s.png",  'whole' => 2 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => '14M 57mm Thermal Paper roll for Small Printers (Fawry POS)', 'ItemName' => 'بكر حراري 14 متر 5.7 سم للطابعات الصغيرة (ماكينات فوري)', 'ItemImageWhole' => 'products/29.png', 'POSTP' => '326.4', 'POSPP' => '1.7', 'MinorPerMajor' => '192', 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 1],
            ['ItemImage' => "products/30s.png",  'whole' => 2 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => '16M 57mm Thermal Paper roll for Small Printers (Fawry POS)', 'ItemName' => 'بكر حراري 16 متر 5.7 سم للطابعات الصغيرة (ماكينات فوري)', 'ItemImageWhole' => 'products/30.png', 'POSTP' => '319.2', 'POSPP' => '1.9', 'MinorPerMajor' => '168', 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 1],
            ['ItemImage' => "products/31s.png",  'whole' => 2 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => '18M 57mm Thermal Paper roll for Small Printers (Fawry POS)', 'ItemName' => 'بكر حراري 18 متر 5.7 سم للطابعات الصغيرة (ماكينات فوري)', 'ItemImageWhole' => 'products/31.png', 'POSTP' => '361.2', 'POSPP' => '2.15', 'MinorPerMajor' => '168', 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 1],
            ['ItemImage' => "products/23s.png",  'whole' => 2 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => '28M 57mm Thermal Paper roll for Small Printers (Fawry POS)', 'ItemName' => 'بكر حراري 28 متر 5.7 سم للطابعات الصغيرة (ماكينات فوري)', 'ItemImageWhole' => 'products/23.png', 'POSTP' => '403.2', 'POSPP' => '3.36', 'MinorPerMajor' => '120', 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 1],
            ['ItemImage' => "products/24s.png",  'whole' => 2 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => '40M 57mm Thermal Paper roll for Small Printers (Fawry POS)', 'ItemName' => 'بكر حراري 40 متر 5.7 سم للطابعات الصغيرة (ماكينات فوري)', 'ItemImageWhole' => 'products/24.png', 'POSTP' => '384', 'POSPP' => '4.8', 'MinorPerMajor' => '80', 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 1],
            ['ItemImage' => "products/25s.png",  'whole' => 2 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => '4*6 cm 450 Label thermal sticker roll (For Barcode Scales)', 'ItemName' => 'بكر لاصق 4*6 سم 450 ملصق (لموازين البار كود)', 'ItemImageWhole' => 'products/25.png', 'POSTP' => '1150', 'POSPP' => '11.5', 'MinorPerMajor' => '100', 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 1],
            ['ItemImage' => "products/26s.png",  'whole' => 2 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => '4*5 cm 450 Label thermal sticker roll (For Barcode Scales)', 'ItemName' => 'بكر لاصق 4*5 سم 450 ملصق (لموازين البار كود)', 'ItemImageWhole' => 'products/26.png', 'POSTP' => '1050', 'POSPP' => '10.5', 'MinorPerMajor' => '100', 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 1],
            ['ItemImage' => "products/32s.png",  'whole' => 2 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => 'Barcode thermal printer labels roll 4*2.5cm 1500 label (non-Splited)', 'ItemName' => 'بكر لاصق لطابعات الباركود 1500 ملصق 4*2.5سم (غير مقسوم)', 'ItemImageWhole' => 'products/32.png', 'POSTP' => '1344', 'POSPP' => '16', 'MinorPerMajor' => '84', 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 1],
            ['ItemImage' => "products/33s.png",  'whole' => 2 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => 'Barcode thermal printer labels roll 4*2.5cm 1500 label (Splited)', 'ItemName' => 'بكر لاصق لطابعات الباركود 1500 ملصق 4*2.5سم ( مقسوم)', 'ItemImageWhole' => 'products/33.png', 'POSTP' => '1344', 'POSPP' => '16', 'MinorPerMajor' => '84', 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 1],
            ['ItemImage' => "products/1.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => 'Datalogic Magellan MultiDimensional Rays Barcode Scanner', 'ItemName' => 'قارئ باركود ماجيلان من داتا لوجيك متعدد الأشعة', 'ItemImageWhole' => 'products/1.png', 'POSTP' => '4950', 'POSPP' => '4950', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/2.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => 'Datalogic QuickScan lite Handheld Barcode Scanner', 'ItemName' => 'قارئ باركود كفي كويك سكان من داتا لوجيك', 'ItemImageWhole' => 'products/2.png', 'POSTP' => '975', 'POSPP' => '975', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/3.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => 'SunMi-POSThings certified HandHeld 2D Imager', 'ItemName' => 'سن مي - بي او اس ثيجز قارئ باركود كفي ثنائي الأبعاد', 'ItemImageWhole' => 'products/3.png', 'POSTP' => '850', 'POSPP' => '999', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/4.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '0' ,'ItemNameEn' => 'POSThings MultiDimensional Standing Barcode Scanner', 'ItemName' => 'بي او اس ثينجز قارئ باركود مكتبي متعدد الأبعاد', 'ItemImageWhole' => 'products/4.png', 'POSTP' => '3950', 'POSPP' => '3950', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/5.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'Dibal OPOS compatible Checkout scale', 'ItemName' => 'ميزان تشك اوت يعمل مع نظام اوبوس من ديبال', 'ItemImageWhole' => 'products/5.png', 'POSTP' => '5500', 'POSPP' => '5500', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/6.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'Mettler Toledo Ariva checkout scales - OPOS compatible', 'ItemName' => 'ميزان تشك اوت اريفا يعمل مع نظام اوبوس من ميتلر توليدو', 'ItemImageWhole' => 'products/6.png', 'POSTP' => '7500', 'POSPP' => '7500', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/16.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'Rongata RLS Series Labeling scale 6x4', 'ItemName' => 'ميزان بار كود 6*4 طراز RLS من رونجتا', 'ItemImageWhole' => 'products/16.png', 'POSTP' => '7500', 'POSPP' => '7500', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/17.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'Dibal DFS Series Labeling scale', 'ItemName' => 'ميزان بار كود يعمل مع DFS من ديبال', 'ItemImageWhole' => 'products/17.png', 'POSTP' => '14500', 'POSPP' => '14500', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/18.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'POSThings MCR Labeling scale', 'ItemName' => 'ميزان باركود من بي او اس ثينجز طراز MCR', 'ItemImageWhole' => 'products/18.png', 'POSTP' => '6500', 'POSPP' => '6500', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/21.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'Star TSP100 Series 80mm Receipt printer', 'ItemName' => 'طابعة حرارية 80 مم TSP100 من ستار', 'ItemImageWhole' => 'products/21.png', 'POSTP' => '2500', 'POSPP' => '2500', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/20.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'POSThings PT80C 80mm Receipt printer', 'ItemName' => 'طابعة حرارية 80 مم PT80C من بي او اس ثينجز', 'ItemImageWhole' => 'products/20.png', 'POSTP' => '1400', 'POSPP' => '1400', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/19.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'POSThings Essensials Cash Drawer', 'ItemName' => 'درج النقدية اسينشالز من بي او اس ثينجز', 'ItemImageWhole' => 'products/19.png', 'POSTP' => '600', 'POSPP' => '600', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/7.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'Price Checker hardware Kit by POSThings', 'ItemName' => 'مجموعة مستكشف الأسعار من بي او اس ثينجز', 'ItemImageWhole' => 'products/7.png', 'POSTP' => '3999', 'POSPP' => '3999', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/8.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'Honeywell EDA51 Handheld Computer', 'ItemName' => 'كمبيوتر كفي EDA51 من هاني ويل', 'ItemImageWhole' => 'products/8.png', 'POSTP' => '6250', 'POSPP' => '6250', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/9.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'POSThings 15 inch touch screen for Retail purposes', 'ItemName' => 'شاشة تعمل باللمس الحراري 15 بوصة من بي او اس ثينجز', 'ItemImageWhole' => 'products/9.png', 'POSTP' => '3000', 'POSPP' => '3000', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/10.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'Diebold Nexdorf Beetle German All in one Point of sale computer 15 inch', 'ItemName' => 'كمبيوتر الكل في واحد لنقاط البيع 15 بوصة يعمل باللمس من دايبولد نيكسدورف', 'ItemImageWhole' => 'products/10.png', 'POSTP' => '25000', 'POSPP' => '25000', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => '0', 'GroupCode' => 2],
            ['ItemImage' => "products/11.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'Elo All in one point of sale computer 14 inch', 'ItemName' => 'كمبيوتر الكل في واحد لنقاط البيع 14 بوصة يعمل باللمس من ايلو', 'ItemImageWhole' => 'products/11.png', 'POSTP' => '9999', 'POSPP' => '9999', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => '0', 'GroupCode' => 2],
            ['ItemImage' => "products/12.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'Dell Optiplex POS Ready small PC', 'ItemName' => 'جهاز كمبيوتر لنقاط البيع اوبتيبليكس من ديل', 'ItemImageWhole' => 'products/12.png', 'POSTP' => '1999', 'POSPP' => '1999', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/13.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'Multipurpose Display', 'ItemName' => 'شاشة متعددة الأغراض', 'ItemImageWhole' => 'products/13.png', 'POSTP' => '750', 'POSPP' => '750', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/14.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'POSThings Computing kit', 'ItemName' => 'مجموعة الكمبيوتر من بي او اس ثينجز', 'ItemImageWhole' => 'products/14.png', 'POSTP' => '2999', 'POSPP' => '2999', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
            ['ItemImage' => "products/15.png",  'whole' => 0 , 'latest' => '1', 'bestseller' => '1' ,'ItemNameEn' => 'POSThings Complete POS Starter Kit', 'ItemName' => 'المجموعة الكاملة لنقاط البيع من بي او اس ثينجز', 'ItemImageWhole' => 'products/15.png', 'POSTP' => '5950', 'POSPP' => '5950', 'MinorPerMajor' => 1, 'ActiveItem' => 1, 'InStock' => 1, 'GroupCode' => 2],
        ];
        foreach($items as $item) {
            $item['ItemNameEnWhole'] = 'package ' . $item['ItemNameEn'];
            $item['ItemNameWhole'] = 'كرتونة ' . $item['ItemName'];
            Product::create($item);
        }
        // Product::insert($items);
      }
}
